### ISSUE TITLE
Discussion: dev builds by default

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#144]
It can potentially be confusing to a user that `ionic run` and `ionic emulate` do prod builds by default and `ionic serve` does dev builds by default without explicitly passing the `--dev` flag or the `--prod` flag.

**Comment by Bouzmine** [comment]
@jgw96 I think `@ionic/app-scripts` behaviour is OK. The default behaviour makes things work as fast as they can by default and this is less confusing than to have to search how to enable AoT compiling or minification. The default behaviour also makes sure that when you are testing on device, you get the same environment by default as a user would.

**Comment by danbucholtz** [comment]
@jgw96,

In addition to that, the current behavior is challenging to tell what's going on since we don't create source maps. It makes working with Cordova, a major part of our ecosystem, quite painful.

We should update the default behavior for running on device/emulator to be more like development mode but with NGC, and then also have a notion of a release/production build that does minification, doesn't build source maps, etc. The release/production build would be laser focused on performance, where as the other builds are more geared towards a great developer experience.

Thanks,
Dan

**Comment by marcoturi** [comment]
this bheaviour can produce also this issue -> https://github.com/marcoturi/ionic2-boilerplate/issues/10 
I was trying to force ionic run to build only in dev mode, and i got that error. The solution is vary ugly to me:

> "build --dev": "npm run build --dev",

**Comment by kashban** [comment]
In addition to @marcoturi you may change your package.json to this:

>         "emulate:before": "build --dev",

That way all builds to be emulated will be dev builds and AOT is no longer an issue. Same goes for "run:before" if you like.
