### ISSUE TITLE
ReactiveForms not work with AOT

### ISSUE THREAD

**Issue by nicobytes** [driftyco/ionic-app-scripts#156]
#### NGC not work

![screenshot from 2016-10-13 18-09-31]

## Error

![screenshot from 2016-10-13 18-09-31](https://cloud.githubusercontent.com/assets/7611944/19374014/2c5c1280-918e-11e6-8c2c-83a42802901b.png)

## class.ngfactory.ts

![screenshot from 2016-10-13 18-10-39](https://cloud.githubusercontent.com/assets/7611944/19373986/d78ec306-918d-11e6-9a62-dfd163576ce9.png)

is a simple form

```js
buildForm() {
    return this.formBuiler.group({
      'user': ['',Validators.required],
      'password': ['', Validators.required ]
    })
  }
```

**Steps to reproduce:**
1.Create  ReactiveForm
2.Ionic build 
3.Error

**Comment by danbucholtz** [comment]
Hi @nicobytes,

This looks like a bug in your code.  I can't immediately identify it, but I can tell you that `ngc` from Angular is very strict and it would be best to initialize those properties right away on the component instead of via a function or something.

I would play around with that sort of approach until you find something that works.  Otherwise, you could always ask the question on our [Ionic community](https://forum.ionicframework.com/?utm_source=framework&utm_medium=navbar&utm_campaign=forum%20CTA). People are very helpful there.

Since this isn't an Ionic or App-scripts bug, I'm going to close this for now. Let us know if you can get it figured out!

Thanks,
Dan

**Comment by nicobytes** [comment]
mm but all the files in the folder .tmp are created by ionic-app-scripts (ngc) and error is in the file myclass.ngfactory.ts inside the folder .tmp. (result of ngc proccess)

the error is in the reference a user (field of form)
```
this.context.formLogin.controls.user.dirty
```

but the right  is:

```
this.context.formLogin.controls['user'].dirty
//or
this.context.formLogin.controls.find('user').dirty
```

but the file myclass.ngfactory.ts is create for ngc process not by me
