### ISSUE TITLE
bug: debugging in browser (sourcemap)

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-app-scripts#175]
#### Short description of the problem:
Often I come across the following:

- No source map available and as such cannot view the source document. Shows me weird ngfactory.js files instead of my source. 
- Inability to place breakpoints in the ts source in Chrome when the source document is available. The ability to add breakpoints and debug code sometimes is allowed in areas, and sometimes not.  

![image](https://cloud.githubusercontent.com/assets/2852839/19411304/83c47d74-92ff-11e6-9d2a-c4cfef6c6429.png)

In the screenshot above, I can find my ts code in Chome, however for some unknown reason I am not able to breakpoint or investigate any methods.

#### What behaviour are you expecting?
I really am expecting to be able to debug my code while running `ionic serve`. This used to work flawlessly prior to RC0.

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.34
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.8.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by dylanvdmerwe** [comment]
Restarting the `ionic serve` option and reopening the browser then allows me to breakpoint. At least for a while.

![image](https://cloud.githubusercontent.com/assets/2852839/19411344/5052648c-9300-11e6-8da6-1e183118fa15.png)

**Comment by andrevcf** [comment]
same here running npm run watch

**Comment by rathgeber2** [comment]
could be linked to #191

**Comment by rathgeber2** [comment]
with latest i am able to debug, the problem was that i blocked polyfilljs and some other scripts in chrome dev console, i unblocked them and the src folder shows up

**Comment by jgw96** [comment]
Hello everyone! The latest beta release of app-scripts, which you can install using `npm install @ionic/app-scripts@beta --save`, does have source maps. Because of this I am going to close this issue for now. For full disclosure though we are steady working on improving our source maps. At the moment the source maps you will see are coming from webpack. While these source maps work, the source maps generated by TypeScript are better and therefore we are working on replacing the WebPack source maps with the TypeScript ones. Thanks!
