### ISSUE TITLE
0.0.37-2 change function parameters not reloaded

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-app-scripts#277]
Hey,

With version 0.0.37-2, when the server is running (ionic serve), if I add a parameter to a function and forget to add the new parameter to the calling object, this error not gonna be noticed

Let's say I'fe go a method

```
foo(object1:MyObject) {}
```

called somewhere in my code

```
myObject.foo(object1);
```

If I start the server, all good. Then if change the method declaration like following and forget to change the caller

```
  foo(object1:MyObject, object2:MyObject) {}

  myObject.foo(object1);
```

The automatic compilation gonna start but doesn't gonna notice any errors till I restart my server fully.

But maybe you already solved it? Or maybe that isn't an error at all.

P.S.: Of course my example with one function and one caller is silly ;)

**Comment by danbucholtz** [comment]
@peterpeterparker,

So here's what would happen:

If you make a change that won't compile, Ionic serve will still refresh and log the error to the console output. We are not directly error checking on re-builds to make it fast. We *are* error checking in a separate background thread. In the coming weeks, we will be pushing out updates to the browser letting you know there is a build error.

I'll keep this issue open for now since to track the status of push notifications during development for `ionic serve`.

Thanks,
Dan

**Comment by peterpeterparker** [comment]
@danbucholtz thx for the explanations!

**Comment by nikoTM** [comment]
Hey @danbucholtz, should I create a separate ticket for 0.0.37-2 not reloading on template changes ?

**Comment by danbucholtz** [comment]
@nikoTM,

No, go ahead and update to `0.0.39`. This issue is fixed.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I am going to close this issue and track the "error message pushed to browser" thing here instead.

https://github.com/driftyco/ionic-app-scripts/issues/294

Thanks,
Dan
