### ISSUE TITLE
bundle failed with moment.js

### ISSUE THREAD

**Issue by iron9light** [driftyco/ionic-app-scripts#28]
Got this error message:
bundle prod failed:  Error: Cannot call a namespace ('moment')

+-- @angular/common@2.0.1
+-- @angular/compiler@2.0.1
+-- @angular/compiler-cli@0.6.3
+-- @angular/core@2.0.1
+-- @angular/forms@2.0.1
+-- @angular/http@2.0.1
+-- @angular/platform-browser@2.0.1
+-- @angular/platform-browser-dynamic@2.0.1
+-- @angular/platform-server@2.0.1
+-- @ionic/app-scripts@0.0.21
+-- @ngrx/core@1.2.0
+-- @ngrx/effects@2.0.0-beta.3
+-- @ngrx/store@2.2.1
+-- @types/lodash@4.14.36
+-- @types/pouchdb-core@5.4.5
+-- immutable@3.8.1
+-- ionic-angular@2.0.0-beta.11-201609260323 invalid
+-- ionic-native@2.0.3
+-- ionicons@3.0.0
+-- lodash@4.16.2
+-- mdi@1.7.22
+-- moment@2.15.1
+-- pouchdb-core@5.4.5
+-- rxjs@5.0.0-beta.12
+-- typescript@2.0.3
`-- zone.js@0.6.25

**Comment by shlomiassaf** [comment]
How can someone understand from this description, hi man open source give a little take some :) make an effort.

Anyway, I ran into you'r issue so I don't need much:
duplicate to #16 

This semi-workaround will make it work on dev builds:
```
import moment from 'moment';
```
**This will not work on production build, `ngc` will throw (it gets ignored on dev)**

The core issue is with rollup build handling CommonJS modules.

When doing:
```
import * as moment from 'moment'
```
You satisfy typescript (and you write the correct import statement) but in the bundling process **rollup** will mis handle this package and make `moment` the module itself with a `default` property that is the `moment` function.

This is why you get the error.

In the "semi-workaround" you actually import using a statement rollup would expect so everything is fine (remember TS will output ES6 to rollup)

Now you can run in dev but you will see a TS error since you import incorrectly.

**Comment by danbucholtz** [comment]
Hi @iron9light 😄 ,

This is a duplicate as @shlomiassaf noted. We are aware of the issue. We will fix it.

@shlomiassaf - no need to be rude to @iron9light.  Please follow our [code of conduct](https://github.com/driftyco/ionic/blob/master/CODE_OF_CONDUCT.md).

I'm going to close this issue and work off of the original.

Thanks,
Dan

**Comment by iron9light** [comment]
@danbucholtz Thank you and this friendly community.
@shlomiassaf Thank you for your explain, and reminding. I will do more homework before next issue. Trust me, I do know what contribution mean.
