### ISSUE TITLE
Jade templates (or others) support

### ISSUE THREAD

**Issue by sonic182** [driftyco/ionic-app-scripts#31]
There is any way to support Jade templates (or others)? I used to extend gulpfile with a task from previously version of ionic, but now better if it can be done with this tool

**Comment by adamdbradley** [comment]
You should be able to use you're own rollup config, and add a rollup jade plugin to it: https://github.com/rollup/rollup/wiki/Plugins

However, this is not something we'll be supporting out of the box with Ionic. Thanks

**Comment by sonic182** [comment]
Ok nice, looks that I can use pug plugin for jade templetes

**Comment by valdisz** [comment]
Hi!

As I have understood, it is needed to modify how view templates are inlined into resulting JS code. Inlining is done (was done till yesterday) by internal Rollup plugin `ng-template`. There is existing Rollup plugin (https://github.com/cebor/rollup-plugin-angular) who can inline templates and allows to use transpilers, but I have not yet tried to do it yet instead of `ng-template`.

Also _now_ process is changed and there are no "ng-template" plugin anymore, so all my investigation was just waste of time :(

**Comment by tycho01** [comment]
@valdisz: Hm. If I'm not mistaken, Rollup plugins like that would still suffer from my issue of only getting invoked after ionic-app-scripts has failed to copy over the relevant template files, no? If you do manage to get this working in the Ionic 2 RC context though, I'd be pretty curious!

**Comment by valdisz** [comment]
@tycho01 After some more investigation I tend to think that only way how to support HTML transpilers like Pug, is to run parallel process before Ionic build, which will transpile `pug` sources into `html`. Because in prod mode they run `ngc` which don't have any extension points and in dev mode Rollup plugin from Ionic will fire first regardless of supplied configuration. I will try to implement this approach using Gulp and hooks.

**Comment by valdisz** [comment]
Got working solution with Pug and Gulp. Here (https://github.com/valdisz/ionic2-pug) is demo app.

**Comment by MaciejCaputa** [comment]
Is there a possibility to add a custom webpack config that process pug files?

**Comment by tycho01** [comment]
@MaciejCaputa I've customized the webpack build for app-scripts to enable async-await using an extra babel compilation step, but they run it after the other steps (including tsc/rollup).
By that point the files are no longer where you'd want it to look for them -- see my comment above on app-scripts' TS compiler first copying over everything needed for TS compilation, so excluding other files you might want around.
I'd settled on an extra gulp step, though I'm kind of unhappy about the dozens of dependencies it brings. That said, if you're not using plugins for Pug, the pug cli itself might help you as well.
