### ISSUE TITLE
getTemplatesTypescriptFile should support javascript as well

### ISSUE THREAD

**Issue by stalniy** [driftyco/ionic-app-scripts#317]
#### Short description of the problem:
Currently `getTemplatesTypescriptFile` function works only with typescript extensions, so people who wants to use js can't take advantage of predefined build tools

#### What behavior are you expecting?
`getTemplatesTypescriptFile` should be renamed to `getTemplatesFile` and take extensions from package config. So, then I can put in my package.json

```js
{
  "config": {
    "files_to_parse": [".ts", ".js"]
  }
}
```

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
0.0.39

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! We made the decision to go all in with TypeScript with Ionic 2 and focus all our build and development work using and supporting TypeScript because of all the [benefits it provides you as a developer](http://ionicframework.com/docs/v2/resources/typescript/). Because of this, at this time we are only supporting using TypeScript with app-scripts and do not have plans to support plain JavaScript. Sorry for any hassle this causes!
