### ISSUE TITLE
Not happy with ionic-app-scripts

### ISSUE THREAD

**Issue by JoeKool** [driftyco/ionic-app-scripts#36]
Very disappointed with the new build scripts. 
1. Slower build process due to unnecessary "templateUpdate" and "bundle dev update" steps during live reload.
2. Difficult to debug main.js compared to individual script files
3. Gulp has so many plugins to customise build, do I have to roll out my own javascript config.js files now?
4. Treating www folder as a build folder (to be cleaned up) is not a good idea. I have some very large data files to be kept inside www folder, copying them during build is not an option.

**Comment by danbucholtz** [comment]
Hi @JoeKool,

I'm really glad to hear your feedback. We know we need to make some improvements here.

Gulp isn't an option because it is effectively abandoned. It hasn't been updated in months and has all sorts of bugs and deprecation warnings and the community leaves it behind.

We are going to continue to iterate on this and make it better.  App scripts is the future.

Once again, thanks for your feedback! It mirrors what some others have said and believe me, we hear you loud and clear.

Thanks,
Dan

**Comment by pskhodad** [comment]
On wiping www folder I had filed #33. I had same opinion as @JoeKool. But on second thought realized that you don't need to put www under version control. But looking at above use case, not putting just one folder under version control doesn't seem to be huge benefit.

**Comment by mlynch** [comment]
Thanks for the feedback! We have filtered it and will watch this. Going to close this issue for now, if you have specific things we can fix we hope you'll file more issues for those. For now, consider your feedback received and we're discussing it for the next release.

Also one reason we moved to app scripts was to hopefully dramatically cut down on the amount of dependencies we package, which also led to install issues and slow downs. It's going to be a bit of process but with a few of the initial issues fixed I think this would be a different first reception.
