### ISSUE TITLE
Proxy does not work

### ISSUE THREAD

**Issue by abomadi** [driftyco/ionic-app-scripts#445]
proxy settings are not working when running ionic serve command! on 0.45 version or 0.44 however if i put --debug after serve command it works!, any help !

**Comment by moldstadt** [comment]
I am experiencing the same problem, since updating from RC1 to RC3, even with the --debug option.

I have something like this in ionic.config.json:
```
"proxies": [{
		"path": "/root",
		"proxyUrl": "http://path.to.server/root"
	}]
```

If I run "ionic serve", I get a lot of 404 errors in the browser console.  There is also no mention of proxies in the console, like there used to be with older version.

**Comment by moldstadt** [comment]
Ok, I think I have found the issue.  I actually have a few proxies.  Only the first one is working:
```
"proxies": [{
		"path": "/root1",
		"proxyUrl": "http://path.to.server/root1"       <- This one works
	},
	{
		"path": "/root2",
		"proxyUrl": "http://path.to.server/root2"       <- This one doesn't
	},
        ...                                                <- These also don't work
]
```
If I swap them around, it is still only the first one that works.

**Comment by abomadi** [comment]
@moldstadt it seems it's an release issue upgrade to 0.0.46 and you should be fine as this was on there release notes
