### ISSUE TITLE
Intellisense Webstorm doesn't work for angular 2 libraries

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#52]
_From @aavelyn on September 30, 2016 8:52_

#### Short description of the problem:

Webstorm won't show autoimport/autocomplete prompts for angular 2 keywords. I think it's because all @angular dependencies aren't on first level (because of ionic-angular)

Deleting node modules and placing all @angular dependencies before ionic-angular and run npm install solves it, but not sure if it'll create conflicts (shouldn't?)

#### What behavior are you expecting?

Webstorm to shop classic autoimport/autocomplete prompts for @angular keywords 

**Which Ionic Version?** Ionic 2 rc0

_Copied from original issue: driftyco/ionic#8346_

**Comment by denofevil** [comment]
Hi,
Dennis from WebStorm team here.
Right now we're not indexing indirect dependencies due to performance (more modules -> more indexing, slower code insight) and quality issues (irrelevant variants in code completion and navigation).
We can add some custom logic specially for Ionic projects, but it looks somewhat hackish.
Any chance you can add angular as a direct dependency? That way the package.json will give users better insight of the app dependencies. The Create-React-App uses that approach:
```json
{
 "devDependencies": {
   "react-scripts": "0.4.1"
 },
 "dependencies": {
   "react": "^15.3.1",
   "react-dom": "^15.3.1"
 },
}
```
What do you think?

**Comment by jgw96** [comment]
Hello all! We are looking at moving our deps around a little in the RC.1 release and that should resolve this issue. I am going to keep this issue open as a tracking issue until then. Thanks!

**Comment by jthoms1** [comment]
This is the PR that I have that should fix this issue. When we create a base ionic2 it should link to the angular dependencies directly rather than rely on ionic's dependency on angular.  @denofevil Does this should like it should fix the WebStorm issue?

driftyco/ionic2-app-base#87

**Comment by denofevil** [comment]
@jthoms1, looks like it should

**Comment by jgw96** [comment]
@aavelyn this should be fixed by the above PR. Can you change your package.json to match the changes in the above linked PR and try again please? Thanks!

**Comment by jgw96** [comment]
Hello all! I am going to close this issue for now as it should be fixed in the latest release of app-scripts. If you still have issues with this feel free to comment and i will happily reopen. Thanks!
