### ISSUE TITLE
Custom config does not work on Windows

### ISSUE THREAD

**Issue by derTuca** [driftyco/ionic-app-scripts#58]
When trying to set a custom config file for a build step on Windows (for example, rollup.config.js), it will not find the config file, even though it is there. This can be reproduced by both setting a CLI option, or using the config in package.json. It works fine in OS X. Running on Windows 10 x64.

**Comment by adamdbradley** [comment]
Is there an error message that prints out?

**Comment by derTuca** [comment]
It says that the config file at path cannot be found, even though it prints the correct path.

**Comment by pskhodad** [comment]
I think message about config file not found appears to be bit misleading. In my case there was issue with custom rollup config. So custom rollup was indeed found but it errored out due to issue with config.

[23:28:36]  Config file "C:\dev\pwa\roll003\config\rollup.config.js" not found. Using defaults instead.

[23:28:36]  Error: Cannot find module '../dist/plugins/ng-template'

And in my custom rollup I had 
var ngTemplate = require('../dist/plugins/ng-template').ngTemplate;

**Comment by derTuca** [comment]
Oh, that might be an issue, I remember seeing something like that. I'll check when I get home. It works fine in OS X though, so I think the error should be made a bit clearer/the behavior should be reproduced. Thank you for the fix, though.

**Comment by derTuca** [comment]
Oh, that might be an issue, I remember seeing something like that. I'll check when I get home. It works fine in OS X though, so I think the error should be made a bit clearer/the behavior should be reproduced. Thank you for the fix, though.

**Comment by dmastag** [comment]
Got the same exact issue and resolved using the notes from @pskhodad to check the log.
Changed 

```
var ngTemplate = require('../dist/plugins/ng-template').ngTemplate;
```

into
```
const ngTemplate = require('@ionic/app-scripts/dist/plugins/ng-template').ngTemplate;
```

and its now working properly.
