### ISSUE TITLE
Can not auto Compile and reload with docker -v

### ISSUE THREAD

**Issue by oSpring** [driftyco/ionic-app-scripts#620]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
Host is Windows 10,  The image of node:6.9.3/node:7.3.0/node:7.4.0 of docker and ionic:2.1.18(ionic-angular@2.0.0-rc.4) and ionic-app-scripts:0.0.47/ionic-app-scripts:0.0.48

the App dir is in the host, and using -v to mount in docker.

the command is :
`docker run -t -i -p 8080:8080 -v E:\xxx\myapp:/home/myApp/ -w /home/myApp/ xxx/calender:2.1.18-6.4.0 /bin/bash`

myapp is the project created by "ionic start --v2 myApp sidemenu"

#### What behavior are you expecting?
 auto Compile and reload running as expected.

**Steps to reproduce:**
1.using docker and with image node:6.9.3/node:7.3.0/node:7.4.0
2.run 
`docker run -t -i -p 8080:8080 -v E:\xxx\myapp:/home/myApp/ -w /home/myApp/ xxx/calender:2.1.18-6.4.0 /bin/bash`
3. npm install -g ionic; ionic start --v2 myApp sidemenu; rewrite the nonempty dir -> yes; npm install
4. ionic serve -p 8080
5. change and save files.
6. nothing happened.

#### insert any relevant code between the above and below backticks
```
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.9.3
npm info lifecycle ionic-hello-world@~preionic:serve: ionic-hello-world@
npm info lifecycle ionic-hello-world@~ionic:serve: ionic-hello-world@

> ionic-hello-world@ ionic:serve /home/myApp
> ionic-app-scripts serve "--v2" "--port" "8080" "--address" "0.0.0.0" "--livereload-port" "35729"

keywords if/then/else require v5 option
[04:06:07]  ionic-app-scripts 0.0.47
[04:06:07]  watch started ...
[04:06:07]  build dev started ...
[04:06:07]  clean started ...
[04:06:07]  clean finished in 9 ms
[04:06:07]  copy started ...
[04:06:07]  transpile started ...
[04:06:11]  transpile finished in 3.91 s
[04:06:11]  webpack started ...
[04:06:11]  copy finished in 4.29 s
[04:06:22]  webpack finished in 10.63 s
[04:06:22]  sass started ...
[04:06:24]  sass finished in 1.93 s
[04:06:24]  build dev finished in 16.61 s
[04:06:24]  watch ready in 16.71 s
[04:06:24]  dev server running: http://localhost:8080/
```

**Which @ionic/app-scripts version are you using?**
0.0.47/0.0.48

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by ataraxus** [comment]
Hey, I think your issue is probably not ionic related. Please login to your container and change a file in there and you will likely trigger a rebuild. 

Like vagrant, docker (at least the last time i used it it used virtualbox as a driver) doesn't implement the filesystem feature that is needed so the container notices a file change made in the host system. There are plenty workarounds, but none which i found compelling so i ditched vagrant/docker for building ionic :( 

There is an issue for that 6 years old on virtualbox 
https://www.virtualbox.org/ticket/9069

I think they wont fix this, since they want you to buy "professional" virtualization which supports this.

**Comment by metal3d** [comment]
I don't agree @ataraxus answer. I've got the same problem right now (since 1 week), The command specify "-a" or "--address 0.0.0.0" but right now, ionic want to listen "localhost". That is not right, earlier versions was listening 0.0.0.0 address.

So, right now, docker or other host cannot connect to ionic server.

**Comment by ataraxus** [comment]
@oSpring can you confirm my suggestions? 
I think this issue should be closed, since it is not related to ionic

**Comment by oSpring** [comment]
Thank you @ataraxus .
but i search google for much time.
somebody said that setting the webpack watchOption:{poll:true} will be work. but its still not work for me.
so i am still working for it.

**Comment by ataraxus** [comment]
Last Time i checked, the issue was the time stamps didn't updated so watch has no chance even with polling. I remembered that you could use nd a to mount the folder, then polling will do

**Comment by danbucholtz** [comment]
Sounds outside of the scope of Ionic. I hope you can get it fixed.

Thanks,
Dan
