### ISSUE TITLE
Default behaviour --release

### ISSUE THREAD

**Issue by ataraxus** [driftyco/ionic-app-scripts#621]
#### Short description of the problem:
Maybe it just me, but if i run `ionic build android --release` I'm expecting ionic to setup everything so i have a "releasable" apk/ipa. 

But if one does just `ionic build android --release` ionic will mangle the TS sources with the *dev* setup. One must provide the `--prod` option which reads funny: `ionic build android --release --prod` and could be missed.... 

#### What behavior are you expecting?

I would propose if the `--release` option is set ionic-app-scripts do also `--prod` tasks by default. _IF_ someone really wants a "release" with *dev* TS source, one could use  `ionic build android --release --dev`. I think this would be more intuitive. 

**Which @ionic/app-scripts version are you using?**
```
$ ionic info

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4-201701032156
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.1
Xcode version: Not installed
```

**Comment by aggarwalankush** [comment]
Yes, because in [publishing instructions](https://ionicframework.com/docs/guide/publishing.html), there is no mention of `--prod` flag so using prod flag by default in case of `--release` will be in sync with publishing instructions and avoid confusions.

**Comment by danbucholtz** [comment]
@jgw96,

Can you move this to the CLI repo?

@mhartington,

Can we get some updated docs on the 2.0 site?

Thanks,
Dan

**Comment by mhartington** [comment]
https://ionicframework.com/docs/v2/setup/deploying/

Update instructions related to v2 build and releases were added some time ago. The link provided leads to the v1 docs

**Comment by davidquon** [comment]
> https://ionicframework.com/docs/v2/setup/deploying/

@mhartington - This link shows a `404`.  I assume this wasn't intentional?  Thanks.

**Comment by davidquon** [comment]
> Maybe it just me, but if i run ionic build android --release I'm expecting ionic to setup everything so i have a "releasable" apk/ipa.

@ataraxus After following the [Ionic Publishing](https://ionicframework.com/docs/guide/publishing.html) instructions, I agree just missing the `--prod` was causing my app to crash upon launch which was a hard problem to sort out since I couldn't tell if it was a signing or production build problem.  Simply adding the `--prod` and following the rest of the instructions in [Ionic Publishing](https://ionicframework.com/docs/guide/publishing.html) indeed solved my building and signing woes.  I'm all for making the build process more intuitive or at the very least updating the documentation.  👍

**Comment by mhartington** [comment]
Sorry, the url has changed. it is https://ionicframework.com/docs/v2/intro/deploying/
