### ISSUE TITLE
slow launch time

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-app-scripts#670]
_From @philrob on January 13, 2017 9:50_

At ionic (e.g. Dan) you state that improving the launch time of ionic2 is currently your #1 priority.
At the same time ionic have closed and locked issues dealing with this on the basis that 'you're working on it', which to some degree I can understand. Meanwhile, it would appear (from those closed issues) this is also a #1 priority with quite a number of developers who are evaluating hybrid frameworks to choose which one they go forward with. Could I suggest, therefore, that you provide some regular ongoing feedback, or updates specifically on this #1 priority. Maybe this could be added to the overall 'changelog' for new releases of ionic2?

Personally, because every environment is different, I'm using your ionic-conference-app to monitor the situation for my specific environment as it provides a standard 'benchmark' (including for best practices as its developed by yourselves). Currently I experience a launch time for the conference app of ~8 secs on my Nexus 7 (2013) running Android 6.0.1 (both rc4 and rc5), which I'm afraid, I feel is a little too long for me.

I REALLY like ionic for many other VERY important reasons (pedigree, support, documentation, facilities, ...). Also as an experienced developer, I do fully appreciate you have NOT yet reached your final release but, would really like more ongoing feedback on what to expect. Maybe, a specific section in the 'changelog' for each new release candidate?  

_Copied from original issue: driftyco/ionic-conference-app#344_

**Comment by danbucholtz** [comment]
@philrob,

I am not sure exactly what you're looking for. We understand there is an issue here and we're trying to come up with a good short term solution for it. We know what needs to happen long term and are working with Angular to identify the changes they need to make to help us.

Right now we can't tree shake much of the code due to how Angular is distributed. They know this is an issue. We know it's an issue. They're working on the changes on their end. We're working on the changes on our end.

We aren't going to give a timeline because there are too many external dependencies and guesses/theories as to when the issue will be resolve. When a developer does an AoT build, in theory the vast majority of Angular (and Ionic) should be removed from runtime. That is not presently the case so we need to get it working.

Part of the problem is that [treeshaking is completely broken in Webpack](https://github.com/webpack/webpack/issues/2867#issuecomment-269585321).

This is our number one priority. 3 of our team members were in Mountain View last week meeting with Angular, Chrome and Closure Compiler teams to work together to come up with solutions. We have a plan in place that will dramatically reduce the file size and improve start up time - now we need to implement it.

Thanks,
Dan

**Comment by philrob** [comment]
Thanks Dan,

Don't want a lot of detail but, your comments above are certainly informative.. Basically, I would just like to know when you think you done something in this area to make it worth me re-checking my launch time for your conference app (for instance I was surprised/disappointed to see no reduction in launch time between rc4 and rc5, with the --prod option set). Unless you're going to hit ~4 secs (i.e approx half what I experience now) for your conference app (which isn't overly complex) I cannot see potential app users staying around. I'm sure you're also thinking around code splitting to at least show something quickly with rest loading later or via 'lazy loading'. Finally, I just thought the 'changelog' could be a good place for such information.

Good luck with your efforts ...,

Cheers Phil Rob

**Comment by danbucholtz** [comment]
We will certainly hit less than 4 seconds. It all comes down to bundle size right now which is way bigger than it should be.

**Comment by philrob** [comment]
Great! - look forward to it :-)

**Comment by philrob** [comment]
Hi Dan,
Quite surprised to see you move to Ionic 2.0.0 FINAL with your #1 priority (reducing launch time) not fixed yet - guess that's because all frameworks are competing and under severe pressure to get to their FINAL. Anyway, ignoring that fro now, well done to the Ionic Team!
Cheers Phil

**Comment by padmini-grmtech** [comment]
i am facing the same problem. my boot time is 13sec which is unacceptable.Please help me i am using latest ionic. Here is my Info 
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: OS X El Capitan
Node Version: v7.4.0
Xcode version: Xcode 8.2 Build version 8C23
