### ISSUE TITLE
ionic_experimental_manual_treeshaking - can't find variable Badge

### ISSUE THREAD

**Issue by ghenry22** [driftyco/ionic-app-scripts#767]
#### Short description of the problem:
I enabled "ionic_experimental_manual_treeshaking": true in package.json
run ionic build ios --prod
launch my app in the emulator and it hangs on startup with js error:

ReferenceError: Can't find variable: Badge

which is interesting, because I don't use badges anywhere in the app or reference them anywhere in my code, so likely something within the ionic code that is getting a bit messed up with the treeshaking.

all works perfectly when I turn the experimental treeshaking off again.

#### What behavior are you expecting?

app starts as normal without errors

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
1.1.2
ionic v2.0.1
ionic-native 3.0.0-alpha1

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by DavidStrausz** [comment]
Have you tried adding "ionic_experimental_purge_decorators": true? I had a similar error regarding the Chip component that I was not even using, adding this flag fixed it for me.

**Comment by danbucholtz** [comment]
Yes, these two options seem to be set together. Right now it's two flags because it is technically two features that were coded at different times.

When we enable this stuff by default (meaning it's not longer experimental), we'll likely move it to one flag since they're so tightly tied together.

Please let me know if this is still an issue. If you could provide a repository that I can use to reproduce it, that would be extremely helpful. This functionality is well unit tested but I am sure there are scenarios that I did not think of. I can add the tests and fix the problem.

Thanks,
Dan

**Comment by ghenry22** [comment]
@danbucholtz that resolves the "badge" issue thanks.  I was trying one step at a time to try and be more predictable about it, didn't realise they had to go together.  I have a different issue now but will log a new issue
