### ISSUE TITLE
ionic_experimental_manual_treeshaking and ionic_experimental_purge_decorators feedback

### ISSUE THREAD

**Issue by PabloFNK** [driftyco/ionic-app-scripts#775]
**Which @ionic/app-scripts version are you using?**
1.1.3

**Description**

I've been having a look into those two exprimental flags in order to try to see if they were improving the startup time of my app, and this is what I've found.

1. Setting both flags to true

```
"ionic_experimental_manual_treeshaking": true,
"ionic_experimental_purge_decorators": true
```

The app runs but it is not including the font-size change applied to the html tag. I mean, previously a 62.5% font-size is applied to the html tag and no longer is applied. I think it is related with the file ionic-angular\components\typography\typography.scss.

2. Setting just  ionic_experimental_manual_treeshaking to true

`"ionic_experimental_manual_treeshaking": true`

The app doesn't run and in the console displays the next error:

> Console error: Uncaught ReferenceError: Avatar is not defined

3. Setting just ionic_experimental_purge_decorators to true

`"ionic_experimental_purge_decorators": true`

The app runs and looks properly.

Anyway in the cases that te app runs I haven't noticed any improvements.

I hope this is useful.

**Comment by danbucholtz** [comment]
@PabloFNK,

Thanks for your feedback. You can remove decorators while keeping manual treeshaking off, but not the other way around. Doing the manual tree shaking requires removing decorators otherwise you'll have null pointer exceptions.

The CSS thing is a known issue that we're fixing in the framework itself. It should be fixed very soon.

These techniques should shave 5-10% off of the bundle size. Our approach to shrinking the bundle size is to have several different approaches that each remove 5-10%. The sum of parts will be significant.

Thanks,
Dan
