### ISSUE TITLE
RC0 build is freakingly slow to build

### ISSUE THREAD

**Issue by linvi** [driftyco/ionic-app-scripts#96]
From Beta 11 to RC0 the build time has been changed from 4 second to 14 seconds...

I do know that you removed gulp, but what has changed that so drastically increased the build time?

**Comment by ajayambre** [comment]
Running `ionic build android' for a simple tabs starter project is taking ~5 minutes for me.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! I am seeing 11 second builds with `ionic serve` on RC0. `ionic build`, `ionic run` and `ionic emulate` takes longer because we run NGC on production builds to do AoT compiling. Also, we are constantly working on getting our dev build times as fast as possible and hope to have it much faster in the future. Ill keep this issue open to track out progress.

**Comment by linvi** [comment]
Thank you for the feedback but could you let me know why this has increased so much.

`ionic serve` watches used to take 1~1.5 seconds for typescript or html.
Now the same command takes 6~8 seconds for typescript, and 12~20 seconds for html.

And my project is not a big project, as per the hardware, it is very top end.

**Comment by mlynch** [comment]
As @jgw96 mentioned, the major factor here is Angular's Ahead of Time compiling. It's just not that fast. However, that's only necessary for production builds, so we are looking into speeding up the dev build.

Stand by

**Comment by linvi** [comment]
Thank you for the info, I did not understood the problem.
Now I am eagerly waiting for the new building tools!

Continue your great work!

**Comment by adamdbradley** [comment]
Yes the real issue here is `ngc`, which is what does the Ahead of Time compiling for production builds. We're working with the Angular team and they're well aware of the issues and there's work to be done yet with optimizing ngc. The builds will speed up, but what you're seeing right now is we're putting the speed into production app by compiling the template during a build step, rather than doing it all runtime in the within the client side app. Going to close this since we'll be continually working to speed things up, thanks.

**Comment by sfabriece** [comment]
To speed up `ionic run android`, Could ngc be only run when the `--release` flag is set and use JIT in all the other cases?
